### ISSUE TITLE
Add focus state for home page buttons

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2020.code4lib.org#31]
On the home page when using a keyboard to navigate, the sponsor/register/etc buttons should have a focus state so that a user can see where they are in the page. The focus state appears correctly in Chrome but not in Firefox, and is harder to see in Safari.

**Comment by phette23** [comment]
So I think I see what you're describing but I just want to verify. This is the focus state in Chrome:

<img width="279" alt="Screen Shot 2019-10-03 at 12 52 06" src="https://user-images.githubusercontent.com/1024833/66159332-9fea2980-e5dc-11e9-9040-965ce88e401e.png">

Note the light blue outline, I see something similar in Safari. As near as I can tell, this occurs because of these rules that all derive from Bootstrap's `tab-focus` mixin:

```css
.btn:focus, .btn.focus, .btn:active:focus, .btn:active.focus, .btn.active:focus, .btn.active.focus {
    outline: 5px auto -webkit-focus-ring-color;
    outline-offset: -2px;
}
a:focus {
    outline: 5px auto -webkit-focus-ring-color;
    outline-offset: -2px;
}
```

But also this rule in the user agent stylesheet:

```css
:focus {
    outline: -webkit-focus-ring-color auto 5px;
}
```

Whereas Firefox's user agent stylesheet doesn't have a style for `:focus` & it (rightly) doesn't recognize `-webkit-focus-ring-color` as a valid property value for a color:

<img width="344" alt="Screen Shot 2019-10-03 at 13 04 12" src="https://user-images.githubusercontent.com/1024833/66160173-6d413080-e5de-11e9-994b-e4c3b278373d.png">

I'm a little shocked Bootstrap's tab-focus isn't more cross-platform. From the comment in the file, it seems like Firefox may have changed their behavior on this recently. In any case, we need to add our own .btn:focus & a:focus styles I think.
